package nl.frankkie.poketcghelper.supabase

const val supabaseProjectId = "wyaehzssftoxtylprtta"
const val supabaseUrl = "https://wyaehzssftoxtylprtta.supabase.co"
const val supabaseApiKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5YWVoenNzZnRveHR5bHBydHRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMyNTIzNTQsImV4cCI6MjA0ODgyODM1NH0.UhF4YgGVs1wEZ9NeHV4xP4-SBbJ-AGEI4jB3lEP3tek"